# gcp cloud build config

steps:
- name: 'node'
  entrypoint: 'yarn'
- name: 'node'
  entrypoint: 'yarn'
  args: ['build']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['./deploy.sh', '$_ENV', '$TAG_NAME']
